package com.salientCrgt.hudStack.rules

import com.salientCrgt.hudStack.model.*;
import com.salientCrgt.hudStack.bean.*;
import java.util.HashMap;


 rule "Lender ID Check"
 dialect "mvel"
 when
 	errors: HashMap()
 	caivrsLookup: CaivrsLookup ( lenderID.length() != 10 ) 
 then
 	// System.out.println("From DROOL validation - invalid lender ID.");
 	errors.put("Lender ID", "From DROOL validation - invalid lender ID.");
 end
 

 rule "Borrower Check"
 dialect "mvel"
 when
 	errors: HashMap()
 	cad: CaivrsAuthDetail ( caivrsBorrowerList.size == 0 ) 
 then
 	// System.out.println("From DROOL validation - No borrower found.");
 	errors.put("Borrower", "From DROOL validation - No borrower found.");
 end