package com.salientCrgt.hudStack.rules

import com.salientCrgt.hudStack.model.*;
import com.salientCrgt.hudStack.bean.*;
import java.util.HashMap;


 rule "Lender ID Check"
 dialect "mvel"
 when
 	errors: HashMap()
 	caivrsLookup: CaivrsLookup ( lenderID.length() != 10 ) 
 then
 	// System.out.println("Invalid lender ID. (DROOL)");
 	errors.put("Lender ID", "Invalid lender ID. (DROOL)");
 end
 

 rule "Borrower Check"
 dialect "mvel"
 when
 	errors: HashMap()
 	cad: CaivrsAuthDetail ( caivrsBorrowerList.size == 0 ) 
 then
 	// System.out.println("No borrower found. (DROOL)");
 	errors.put("Borrower", "No borrower found. (DROOL)");
 end